# Site settings
title: Digitalife
header-img: img/home-bg.jpg
email: nguyencongvu@gmail.com
copyright_name: Your/Project/Digitalife.top
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/business"
url: "https://digitalife-top.github.io"
twitter_username: vunc
github_username:  digitalife-top
facebook_username:  nguyencongvu
email_username:  nguyencongvu@gmail.com

og_image: "/images/logo.png" # Open Graph/Twitter default site image

#more to SEO 
twitter:
  username: vunc

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: none #date pretty ordinal 
paginate: 5
paginate_path: "blogs/page:num/"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: 
  - jekyll-paginate
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "bootstrap/page"  
      author: "Vu, Nguyen"
      #header-img: "img/contact-bg.jpg"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "bootstrap/post"  
      author: "Vu, Nguyen"
