# Site settings site.title
title: Digitalife
header-img: img/home-bg.jpg
email: nguyencongvu@gmail.com
copyright_name: Your/Project/Digitalife.top
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/business"
url: "https://digitalife-top.github.io"
author: "Vu, Nguyen"
language: "en" #vi
locale: "en-US" #vi-VN

twitter_username: vunc
github_username:  digitalife-top
facebook_username:  nguyencongvu
facebook_app_id:  "303370230021409"
facebook_admins: "791078183"
email_username:  nguyencongvu@gmail.com

og_image: "img/small/logo.jpg" # Open Graph/Twitter default site image


# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

google_site_verification : "UQj93ERU9zgECodaaXgVpkjrFn9UrDMEzVamacSoQ8Y"
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :


# Build settings
markdown: kramdown
highlighter: rouge
permalink: none #date pretty ordinal 
paginate: 5
paginate_path: "blogs/page:num/"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: 
  - jekyll-paginate
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "bootstrap/page"  
      author: "Vu, Nguyen"
      #header-img: "img/contact-bg.jpg"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "bootstrap/post"  
      author: "Vu, Nguyen"
